"""Tool capability table for the manuscript.

Replaces the two Figure 1 panels that plotted every tool but fastder at zero.
Only fastder emits multi-exon structure or assigns a strand, so those bars drew
a capability as if it were a measurement. A table states it without implying a
score.

Every cell describes code rather than a measurement and carries its source in
CELLS below. A qualified capability is qualified in the cell, not in a footnote.

Writes tool_capabilities.csv and tool_capabilities.tex into the figure
directory. The .tex holds a tabular only; the caption belongs to the paper.

Usage:
    python make_capability_table.py <out_dir>
"""
import csv
import os.path as op
import sys

COLUMNS = [
    "Calls regions by a coverage threshold",
    "Bridges gaps below the threshold",
    "Snaps boundaries to splice junctions",
    "Emits multi-exon structure",
    "Assigns strand",
    "Fits a differential-expression model",
]

TOOLS = ["fastder", "derfinder", "megadepth baseline", "groHMM"]

# Cell values, with the source each was read from.
CELLS = {
    "fastder": [
        # Averager::find_ERs keeps bases whose CPM is above min_coverage.
        "yes",
        # find_ERs breaks the region on a gap or a non-contiguous step, so
        # nothing below the threshold is bridged by coverage. Introns are
        # crossed by junction stitching instead, which is the next column but
        # one.
        "no, junctions instead",
        # Integrator::write_to_gtf snaps to the junction recorded during
        # chaining. Edges with no adjacent junction, the outer ends of a chain
        # and both ends of a monoexonic region, keep the coverage extent.
        "internal edges of chains only",
        # Integrator::stitch_up emits chains of two or more regions.
        "yes",
        # stitch_one_strand tags each chain with the strand of the junctions
        # that built it; unchained regions are emitted with strand '.'.
        "yes, stitched regions only",
        "no",
    ],
    "derfinder": [
        # run_derfinder.R --cutoff, in CPM.
        "yes",
        # run_derfinder.R --maxregiongap.
        "yes",
        "no",
        "no",
        # Run unstranded here, as the other coverage tools are.
        "no",
        # derfinder's published purpose is single-base-resolution differential
        # expression. Not exercised in this benchmark, which compares region
        # calling only.
        "yes, not used here",
    ],
    "megadepth baseline": [
        # run_megadepth_baseline.R: one region per maximal run of bases at or
        # above the cutoff.
        "yes",
        "no",
        "no",
        "no",
        "no",
        "no",
    ],
    "groHMM": [
        # detectTranscripts fits a two-state HMM over 50 nt windows; there is
        # no coverage threshold.
        "no, two-state HMM",
        # The transcribed state persists across coverage dips.
        "yes",
        "no",
        "no",
        # groHMM needs separate plus and minus vectors. recount3 coverage is
        # unstranded, so run_grohmm.R feeds the same vector as both and the
        # output is unstranded.
        "needs stranded input",
        "no",
    ],
}

NOTES = [
    "Capabilities are read from the tool sources and from the runner scripts in workflow/scripts, not measured.",
    "fastder snaps only the internal edges of a multi-exon chain: the snap coordinate is the junction recorded during chaining, so the outer ends of a chain and both ends of a monoexonic region keep their coverage extent.",
    "derfinder's differential-expression model is outside the scope of this benchmark, which compares region calling.",
]


def latex_escape(value):
    return value.replace("_", r"\_").replace("%", r"\%")


def write_csv(path):
    """Long format: one row per tool and capability."""
    with open(path, "w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["tool", "capability", "value"])
        for tool in TOOLS:
            for i, column in enumerate(COLUMNS):
                writer.writerow([tool, column, CELLS[tool][i]])


def tool_header(tool):
    return r"\texttt{" + latex_escape(tool) + "}" if " " not in tool else latex_escape(tool)


def write_tex(path):
    """Capabilities as rows, tools as columns: six short columns of prose fit
    the page width, where six rotated headers over qualified cells do not."""
    lines = ["% Generated by workflow/scripts/figures/make_capability_table.py.",
             "% Tabular only: the caption belongs to the manuscript. Suggested notes:"]
    lines += [f"%   {note}" for note in NOTES]
    lines.append(r"\begin{tabular}{p{0.28\textwidth}" + "l" * len(TOOLS) + "}")
    lines.append(r"\toprule")
    lines.append(" & ".join([""] + [tool_header(t) for t in TOOLS]) + r" \\")
    lines.append(r"\midrule")
    for i, column in enumerate(COLUMNS):
        row = [latex_escape(column)] + [latex_escape(CELLS[t][i]) for t in TOOLS]
        lines.append(" & ".join(row) + r" \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else "."
    write_csv(op.join(out_dir, "tool_capabilities.csv"))
    write_tex(op.join(out_dir, "tool_capabilities.tex"))
    print("wrote tool_capabilities.csv and tool_capabilities.tex in", out_dir)


if __name__ == "__main__":
    main()
