"""Versions of the tools a run used, read from what is installed.

Conda packages are read from the built environments, fastder from its git
checkout, ASimulatoR from a file its container rule writes. A tool whose
environment is not built is left out.

Usage:
    python collect_tool_versions.py --conda-dir <dir> --envs-dir <dir> \
        --fastder-src <dir> [--asimulator-version <file>] \
        --out-csv <csv> --out-tex <tex>
"""
import argparse
import csv
import json
import os.path as op
import subprocess
from glob import glob

# Tool label, environment file in workflow/envs without .yaml, conda package.
CONDA_TOOLS = [
    ("derfinder", "derfinder", "bioconductor-derfinder"),
    ("groHMM", "grohmm", "bioconductor-grohmm"),
    ("R", "derfinder", "r-base"),
    ("STAR", "star", "star"),
    ("samtools", "star", "samtools"),
    ("bedtools", "bedtools", "bedtools"),
    ("gffcompare", "gffcompare", "gffcompare"),
    ("pyBigWig", "megadepth_baseline", "pybigwig"),
]


def read_text(path):
    with open(path) as fh:
        return fh.read()


def environments(conda_dir, envs_dir):
    """Environment file stem to its built directory.

    Snakemake keeps a copy of the environment file as <hash>.yaml beside each
    built <hash>/, so a build is matched to its file by content. Not every
    file declares a name.
    """
    declared = {read_text(path): op.splitext(op.basename(path))[0]
                for path in glob(op.join(envs_dir, "*.yaml"))}
    found = {}
    for yaml_path in sorted(glob(op.join(conda_dir, "*.yaml"))):
        env_dir = yaml_path[: -len(".yaml")]
        stem = declared.get(read_text(yaml_path))
        if stem and op.isdir(env_dir):
            found[stem] = env_dir
    return found


def package_version(env_dir, package):
    """Installed version, or None. The file name alone cannot tell star from
    star-fusion, so the record's own name is checked."""
    for record in sorted(glob(op.join(env_dir, "conda-meta", f"{package}-*.json"))):
        with open(record) as fh:
            meta = json.load(fh)
        if meta.get("name") == package:
            return meta.get("version")
    return None


def git_version(src_dir):
    """`git describe` of a checkout: nearest tag, commits since, commit."""
    result = subprocess.run(["git", "-C", src_dir, "describe", "--tags", "--always"],
                            capture_output=True, text=True)
    return result.stdout.strip() if result.returncode == 0 else None


def read_version_file(path):
    if not path or not op.exists(path):
        return None
    return read_text(path).strip() or None


def collect(conda_dir, envs_dir, fastder_src, asimulator_file=None):
    rows = []
    fastder = git_version(fastder_src)
    if fastder:
        rows.append({"tool": "fastder", "version": fastder, "source": "git"})
    asimulator = read_version_file(asimulator_file)
    if asimulator:
        rows.append({"tool": "ASimulatoR", "version": asimulator, "source": "container"})
    envs = environments(conda_dir, envs_dir)
    for tool, env_name, package in CONDA_TOOLS:
        version = package_version(envs[env_name], package) if env_name in envs else None
        if version:
            rows.append({"tool": tool, "version": version, "source": f"conda:{env_name}"})
    return rows


def write_csv(rows, path):
    with open(path, "w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=["tool", "version", "source"])
        writer.writeheader()
        writer.writerows(rows)


def latex_escape(value):
    return value.replace("_", r"\_").replace("%", r"\%")


def write_tex(rows, path):
    lines = ["% Generated by workflow/scripts/collect_tool_versions.py.",
             "% Tabular only: the caption belongs to the manuscript.",
             r"\begin{tabular}{ll}",
             r"\toprule",
             r"Tool & Version \\",
             r"\midrule"]
    lines += [f"{latex_escape(r['tool'])} & {latex_escape(r['version'])} \\\\" for r in rows]
    lines += [r"\bottomrule", r"\end{tabular}"]
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--conda-dir", required=True)
    parser.add_argument("--envs-dir", required=True)
    parser.add_argument("--fastder-src", required=True)
    parser.add_argument("--asimulator-version")
    parser.add_argument("--out-csv", required=True)
    parser.add_argument("--out-tex", required=True)
    args = parser.parse_args()

    rows = collect(args.conda_dir, args.envs_dir, args.fastder_src, args.asimulator_version)
    write_csv(rows, args.out_csv)
    write_tex(rows, args.out_tex)
    print(f"wrote {len(rows)} rows to {args.out_csv} and {args.out_tex}")


if __name__ == "__main__":
    main()
