"""Generate the derived simulation configs.

config_full_simulation.yaml is the paper-ready default and the 10M point of
the depth sweep. Everything this script writes is a copy of it with one thing
changed, so a change to the simulation block propagates instead of drifting:

- config_full_simulation_<N>M.yaml, the other depths of the sweep.
- config_min_junction_reads_sweep.yaml, the junction read-support sensitivity
  run: the same simulated data, fastder alone, its grid fixed at the shipped
  defaults so min_junction_reads is the only axis that moves.

The depth sweep is declared in DEPTHS_MILLIONS below; edit that list and rerun
the script. Run each config as its own pipeline run (see the Makefile), then
render the cross-depth report with scripts/render_meta_report.sh.

Usage:
    python make_sim_configs.py
"""
import os.path as op
import re

# Depths to generate. 10 is omitted: that is config_full_simulation.yaml itself.
DEPTHS_MILLIONS = [5, 30, 40]

# Junction read-support thresholds, summed over the loaded samples. 0 is the
# published behaviour, in which no junction filter exists at all. The rest
# bracket what a filter does with ten samples per scenario: 1 drops junctions
# seen once across the whole group, 20 keeps only well-supported ones. Recentre
# the ladder if the observed counts turn out to sit elsewhere.
MIN_JUNCTION_READS = [0, 1, 2, 5, 10, 20]

# fastder axes the sweep holds still, at the values shipped in cpp/main.cpp.
# Sweeping them alongside the junction filter would multiply the grid and make
# the sensitivity to the filter itself harder to read.
FIXED_GRID = {
    "min_coverage": "[0.05]",
    "min_length": "[10]",
    "position_tolerance": "[5]",
    "no_stitch": "[false]",
}

# The scaling sweep times fastder against itself on one fixed workload, so it
# belongs to the 10M config alone. Copying it into the other depths would
# repeat the same measurement four times.
SCALING_KEYS = ("scaling_cores", "scaling_scenario")

HERE = op.dirname(op.abspath(__file__))
CONFIG_DIR = op.normpath(op.join(HERE, "..", "..", "config"))
BASE = op.join(CONFIG_DIR, "config_full_simulation.yaml")

KEY = re.compile(r"^(\s*)([A-Za-z_]\w*):")


def section_of(line, current):
    """Track which top-level block a line belongs to."""
    match = KEY.match(line)
    if match and not match.group(1):
        return match.group(2)
    return current


def key_at(line, indent):
    """The key a line declares at the given indent, or None."""
    match = KEY.match(line)
    if match and len(match.group(1)) == indent:
        return match.group(2)
    return None


def write(path, header, lines):
    with open(path, "w") as fh:
        fh.write(header)
        fh.writelines(lines)
    print(f"wrote {path}")


def depth_config(base_lines, depth_m):
    reads = depth_m * 1_000_000
    out, section, pending = [], None, []
    for line in base_lines:
        section = section_of(line, section)
        stripped = line.lstrip()
        if stripped.startswith("#"):
            pending.append(line)
            continue
        if stripped.startswith("seq_depth:"):
            indent = line[: len(line) - len(stripped)]
            out.extend(pending)
            out.append(f"{indent}seq_depth: {reads}  # {depth_m}M reads per sample\n")
        elif section == "fastder" and key_at(line, 2) in SCALING_KEYS:
            # The key goes and its comment block goes with it.
            pending = []
            continue
        else:
            out.extend(pending)
            out.append(line)
        pending = []
    out.extend(pending)
    header = (
        f"# Depth-sweep config: {depth_m}M reads per sample.\n"
        "# Generated by scripts/make_sim_configs.py from\n"
        "# config_full_simulation.yaml. Edit that script, not this file.\n\n")
    return header, out


def junction_sweep_config(base_lines):
    """The base config with fastder's grid pinned and the filter swept."""
    out, section, pending, injected = [], None, [], False
    for line in base_lines:
        previous, section = section, section_of(line, section)
        stripped = line.lstrip()
        if section == "fastder" and previous != "fastder":
            out.append("# fastder alone: this run asks what the junction filter does, not how\n"
                       "# fastder compares with other tools.\n"
                       "tools: [fastder]\n\n")
        if stripped.startswith("#"):
            pending.append(line)
            continue
        if section == "fastder":
            key = key_at(line, 2)
            if key in FIXED_GRID:
                # The swept keys and their comments are replaced wholesale, so
                # nothing carried over describes a grid this config does not have.
                pending = []
                if not injected:
                    out.append("  # Held at the shipped defaults so the filter is the only axis.\n")
                    out.extend(f"  {k}: {v}\n" for k, v in FIXED_GRID.items())
                    out.append("  # Junction read support summed over the loaded samples. 0 is the\n"
                               "  # published behaviour: no junction filter at all, which is what\n"
                               "  # every number in the first submission was produced with.\n")
                    out.append(f"  min_junction_reads: {MIN_JUNCTION_READS}\n")
                    injected = True
                continue
            if key in SCALING_KEYS:
                pending = []
                continue
        out.extend(pending)
        pending = []
        out.append(line)
    out.extend(pending)
    if not injected:
        raise SystemExit("no fastder grid keys found in the base config")
    header = (
        "# Junction read-support sensitivity: the same simulated data as\n"
        "# config_full_simulation.yaml, fastder alone, every parameter but\n"
        "# min_junction_reads held at its shipped default.\n"
        "# Generated by scripts/make_sim_configs.py from\n"
        "# config_full_simulation.yaml. Edit that script, not this file.\n\n")
    return header, out


def main():
    with open(BASE) as fh:
        base_lines = fh.readlines()

    for depth_m in DEPTHS_MILLIONS:
        header, lines = depth_config(base_lines, depth_m)
        write(op.join(CONFIG_DIR, f"config_full_simulation_{depth_m}M.yaml"), header, lines)

    header, lines = junction_sweep_config(base_lines)
    write(op.join(CONFIG_DIR, "config_min_junction_reads_sweep.yaml"), header, lines)


if __name__ == "__main__":
    main()
