"""Generate the depth-sweep configs for the simulation benchmark.

config_full_simulation.yaml is the paper-ready default and the 10M point of
the depth sweep. This script copies it, changing only seq_depth, to produce
the other depths as config/config_full_simulation_<N>M.yaml.

The depth sweep is declared in DEPTHS_MILLIONS below; edit that list and
rerun the script. Run each config as its own pipeline run (see the Makefile),
then render the cross-depth report with scripts/render_meta_report.sh.

Usage:
    python make_sim_configs.py
"""
import os.path as op

# Depths to generate. 10 is omitted: that is config_full_simulation.yaml itself.
DEPTHS_MILLIONS = [5, 30, 40]

HERE = op.dirname(op.abspath(__file__))
CONFIG_DIR = op.normpath(op.join(HERE, "..", "..", "config"))
BASE = op.join(CONFIG_DIR, "config_full_simulation.yaml")


def main():
    with open(BASE) as fh:
        base_lines = fh.readlines()

    for depth_m in DEPTHS_MILLIONS:
        reads = depth_m * 1_000_000
        out_lines = []
        for line in base_lines:
            stripped = line.lstrip()
            if stripped.startswith("seq_depth:"):
                indent = line[: len(line) - len(stripped)]
                out_lines.append(
                    f"{indent}seq_depth: {reads}  # {depth_m}M reads per sample\n")
            else:
                out_lines.append(line)
        header = (
            f"# Depth-sweep config: {depth_m}M reads per sample.\n"
            "# Generated by scripts/make_sim_configs.py from\n"
            "# config_full_simulation.yaml. Edit that script, not this file.\n\n")
        out_path = op.join(CONFIG_DIR, f"config_full_simulation_{depth_m}M.yaml")
        with open(out_path, "w") as fh:
            fh.write(header)
            fh.writelines(out_lines)
        print(f"wrote {out_path}  (seq_depth={reads})")


if __name__ == "__main__":
    main()
