"""Generate the GTEx coverage threshold ladder config.

A copy of config_gtex_comparison.yaml cut down to the first sub-group of each
tissue, with the three tools that take a coverage threshold run over a ladder
of them. The remaining sub-groups play no part in choosing the threshold.

Usage:
    python make_gtex_ladder_config.py
"""
import os.path as op

import yaml

# Coverage thresholds in CPM of the whole library, in 1-2-5 steps.
THRESHOLD_LADDER = [0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1.0]
TOOLS = ["fastder", "derfinder", "megadepth_baseline"]

HERE = op.dirname(op.abspath(__file__))
CONFIG_DIR = op.normpath(op.join(HERE, "..", "..", "config"))
BASE = op.join(CONFIG_DIR, "config_gtex_comparison.yaml")
OUT = op.join(CONFIG_DIR, "config_gtex_threshold_ladder.yaml")

HEADER = (
    "# GTEx coverage threshold ladder: the first sub-group of each tissue of\n"
    "# config_gtex_comparison.yaml, chr19, three tools over a ladder of\n"
    "# min_coverage values, graded against the annotation.\n"
    "# scripts/choose_threshold.py picks the threshold with the best exon-level F1.\n"
    "# Generated by scripts/make_gtex_ladder_config.py from\n"
    "# config_gtex_comparison.yaml. Edit that script, not this file.\n\n")


def first_subgroups(groups):
    """The first sub-group of each tissue, in the order the base config lists them."""
    seen, kept = set(), {}
    for name, group in groups.items():
        if group["study"] not in seen:
            seen.add(group["study"])
            kept[name] = group
    return kept


def ladder_config(base):
    config = dict(base)
    config.pop("benchmark_repeats", None)
    config["recount3"] = dict(base["recount3"], groups=first_subgroups(base["recount3"]["groups"]))
    config["tools"] = TOOLS
    config["fastder"] = dict(base["fastder"], min_coverage=THRESHOLD_LADDER)
    config["threshold_choice"] = True
    return config


def main():
    with open(BASE) as fh:
        base = yaml.safe_load(fh)
    with open(OUT, "w") as fh:
        fh.write(HEADER)
        yaml.safe_dump(ladder_config(base), fh, sort_keys=False, default_flow_style=None)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
